ci:
  - changed-files:
    - any-glob-to-any-file: .github/**

documentation:
  - changed-files:
    - any-glob-to-any-file:
      - docs/**
      - CHANGELOG.adoc
      - LICENSE.txt
      - README.adoc

java:
  - changed-files:
    - any-glob-to-any-file:
      - src/**/java/**/*.java
