name: Verify changelog

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  verify-changelog:
    name: Verify changelog
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v4
      - name: Get changed files
        id: changed-src-files
        uses: tj-actions/changed-files@v44
        with:
          files: src/**/*
      - name: Verify CHANGELOG.md modifications
        id: changed-changelog-md
        if: steps.changed-src-files.outputs.any_changed == 'true'
        uses: tj-actions/changed-files@v44
        with:
          files: CHANGELOG.md
      - name: Fail if changelog was not modified
        if: steps.changed-changelog-md.outputs.any_changed == 'false'
        run: exit 1