name: Dependency submission

on:
  push:
    branches:
      - main

permissions:
  contents: write

concurrency:
  group: ${{github.workflow}}-${{github.ref}}
  cancel-in-progress: true

jobs:
  dependency-submission:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: gradle/actions/setup-gradle@v3
      - uses: gradle/actions/dependency-submission@v3